[tool.poetry]
name = "genai-demo"
version = "0.1.0"
description = "Demo"
authors = ["Mohamed Luqman <luqmandepy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
